#ifndef GRAPHICSFIX_H_INCLUDED
#define GRAPHICSFIX_H_INCLUDED

#include <stdio.h>

#define DASHBOOTS_PEDESTAL_AREA 1
#define DASHBOOTS_PEDESTAL_ROOM 7
#define DASHBOOTS_PEDESTAL_ENTITY 5

#define DOUBLE_PEDESTAL_AREA 1
#define DOUBLE_PEDESTAL_ROOM 22
#define DOUBLE_PEDESTAL_ENTITY 1

#define TACKLE_PEDESTAL_AREA 3
#define TACKLE_PEDESTAL_ROOM 8
#define TACKLE_PEDESTAL_ENTITY 0

#define KICKBOOTS_PEDESTAL_AREA 5
#define KICKBOOTS_PEDESTAL_ROOM 2
#define KICKBOOTS_PEDESTAL_ENTITY 2

#define HEAVYRING_PEDESTAL_AREA 9
#define HEAVYRING_PEDESTAL_ROOM 0
#define HEAVYRING_PEDESTAL_ENTITY 2

#define CLEANSING_PEDESTAL_AREA 8
#define CLEANSING_PEDESTAL_ROOM 21
#define CLEANSING_PEDESTAL_ENTITY 0

#define ROCWING_PEDESTAL_AREA 10
#define ROCWING_PEDESTAL_ROOM 15
#define ROCWING_PEDESTAL_ENTITY 0

#define LASTKEY_PEDESTAL_AREA 12
#define LASTKEY_PEDESTAL_ROOM 0
#define LASTKEY_PEDESTAL_ENTITY 0 

#define ROOM_TYPE_MAGICITEM 0xA

void graphicsFix(FILE* rom);

#endif
