#include <stdio.h>
#include <stdbool.h>
#include "options.h"

int randompatch(FILE* rom, unsigned int randomizer_seed, struct seed_options *options);

// This patch is generated by the randomizer logic and remains in the folder.
#define IPS_RANDOMIZER "Randomizer.ips"

#define SPOILER_FILENAME "spoilerlog.txt"

// This patch grants dash boots at the same time as other initialization steps at
// the beginning of the game without needing to pick them up. Created by DevAnj.
#define IPS_AUTODASHBOOTS "ips/AutoDashBoots.ips"

// This patch allows placing DSS cards on pedestals, prevents them from timing out, and removes them from
// enemy drop tables. Created by DevAnj but drop and pedestal item replacements have been stripped out.
#define IPS_CARDMODE "ips/CardUp_v3_Custom.ips"

// This patch replaces enemy drops that included DSS cards. Created by DevAnj as part of the Card Up patch
// but modified for different replacement drops (lowered rate, potion instead of meat, and no Shinning Armor change on Devil).
#define IPS_NODSSDROPS "ips/NoDSSDrops.ips"

// This patch reveals card combination descriptions instead of showing "???" until the combination
// is used. Created by DevAnj.
#define IPS_CARDCOMBOSREVEALED "ips/CardCombosRevealed.ips"

// In lategame, the Trick Candle and Scary Candle load in the Cerberus and Iron Golem boss rooms after defeating
// Camilla and Twin Dragon Zombies respectively. If the former bosses have not yet been cleared (i.e., we have
// sequence broken the game and returned to the earlier boss rooms to fight them), the candle enemies will cause
// the bosses to fail to load and soft lock the game. This patches the candles to appear after the early
// boss is completed instead. Created by DevAnj.
#define IPS_CANDLEFIX "ips/CandleFix.ips"

// A Tackle block in Machine Tower will cause a softlock if you access the Machine Tower from the Abyss Stairway using the stone tower route with Kick Boots and not Double.
// This is a small level edit that moves that block slightly, removing the potential for a softlock. Created by DevAnj.
#define IPS_BLOCKFIX "ips/SoftlockBlockFix.ips"

// Normally, the MP boosting card combination is useless since it depletes more MP than it gains.
// This patch makes it consume zero MP. Created by DevAnj.
#define IPS_MPCOMBOFIX "ips/MPComboFix.ips"

// Normally, you must clear the game with each mode to unlock subsequent modes, and complete the game at least once to be able to skip the introductory text crawl.
// This allows all game modes to be selected and the introduction to be skipped even without game/mode completion. Created by DevAnj.
#define IPS_GAMECLEARBYPASS "ips/GameClearBypass.ips"

// Patch to add mapping in Underground Gallery and Underground Waterway to avoid softlocking/kick boot requirements. Created by DevAnj.
#define IPS_MAPEDITS "ips/MapEdits.ips"

// Patch to show seed number on start menu. Created by fuse.
#define IPS_SEED_DISPLAY "ips/SeedDisplay.ips"

// Patch to make only the first demo play when on the title screen to avoid leaking info about items. Created by fuse.
#define IPS_DEMO_FORCE_FIRST "ips/DemoForceFirst.ips"

// Patch to allow setting 100% drop rate. Created by fuse.
#define IPS_ALLOW_ALWAYS_DROP "ips/AllowAlwaysDrop.ips"

// Optional patch created by Fusecavator. Permanent dash effect without double tapping.
#define IPS_PERMANENTDASH "ips/PermanentDash.ips"

// Optional patch created by Fusecavator. Blocks switching effects during DSS effect activation to prevent DSS glitching.
#define IPS_DSSGLITCHFIX "ips/DSSGlitchFix.ips"

// Optional patch created by DevAnj. Will activate the flag breaking the Iron Maidens and pressing the switch from the beginning of the game.
#define IPS_IRONMAIDEN "ips/BrokenMaidens.ips"

// Optional patch created by fuse. Allows accumulating multiple last keys and allows restricting the door to a chosen amount.
#define IPS_MULTILASTKEY "ips/MultiLastKey.ips"

// Optional patch created by fuse. Always allow you to use the speed dash Pluto+Griffin card combo, even if you don't have the cards.
#define IPS_ALLOW_SPEED_DASH "ips/AllowSpeedDash.ips"

// Optional patch created by fuse and DevAnj. Doubles damage multipliers of long range familiars.
#define IPS_BUFF_FAMILIARS "ips/BuffFamiliars.ips"

// Optional patch created by Fusecavator. Increases damage of some subweapons and corresponding item crush attacks.
#define IPS_BUFF_SUBWEAPONS "ips/BuffSubweapons.ips"

// Optional patch created by Fusecavator. Increases base strength and strength per level of Shooter mode to match Vampirekiller mode.
#define IPS_SHOOTERSTRENGTH "ips/ShooterStrength.ips"

// Optional patch created by Fusecavator. Allows activating the Pluto + Griffin combo even without the cards obtained.
#define IPS_SPEEDDASH "ips/AllowSpeedDash.ips"

// Optional patch created by fuse. Adds an in-game counter showing the amount of remaining major items in your current area.
#define IPS_COUNTDOWN "ips/Countdown.ips"

// Optional patch created by Fusecavator. Disables the Battle Arena's MP drain effect.
#define IPS_NOMPDRAIN "ips/NoMPDrain.ips"

// Optional patch created by Liquid Cat. The Pluto/Griffin DSS card combination will increase speed even during a jump.
#define IPS_DSSRUNSPEED "ips/DSSRunSpeed.ips"

// Optional patch created by Liquid Cat. The text printed during cutscenes will not appear.
#define IPS_SKIPCUTSCENES "ips/SkipCutscenes.ips"

// Optional patch created by Liquid Cat. The text printed after Magic Items are obtained will not appear.
#define IPS_SKIPMAGICITEMTUTORIALS "ips/SkipMagicItemTutorials.ips"

// Patch created by Fusecavator. Makes changes to dropped item graphics to avoid garbled Magic Items and allow displaying arbitrary items.
#define IPS_DROPREWORK "ips/DropRework.ips"

// Optional patch created by Liquid Cat. Changes the behavior of the Roc Wing depending on which other Magic Items have been obtained.
#define IPS_NERFROCWING "ips/NerfRocWing.ips"

// Patch created by Liquid Cat. Makes Vampire Killer the background music of the Battle Arena, instead of just pure silence.
#define IPS_BATTLEARENAMUSIC "ips/BattleArenaMusic.ips"
