#include "spoilertranslator.h"
#include "addresses.h"

void writePedestal(FILE* spoiler_log, int choice)
{
    char pedestal_rooms[NUMBER_PEDESTALS][8] =
    {
        "SR3",
        "CC1",
        "CC3",
        "CC3B",
        "CC4",
        "CC5",
        "CC8",
        "CC8B",
        "CC9",
        "CC10",
        "CC13",
        "CC14",
        "CC14B",
        "CC16",
        "CC20",
        "CC22",
        "CC24",
        "CC25",
        "AS2",
        "AS3",
        "AS4",
        "AS9",
        "AR4",
        "AR7",
        "AR8",
        "AR9",
        "AR10",
        "AR11",
        "AR14",
        "AR14B",
        "AR16",
        "AR17",
        "AR17B",
        "AR18",
        "AR19",
        "AR21",
        "AR25",
        "AR26",
        "AR27",
        "AR30",
        "AR30B",
        "OW0",
        "OW1",
        "OW2",
        "TH1",
        "TH3",
        "MT0",
        "MT2",
        "MT3",
        "MT4",
        "MT6",
        "MT8",
        "MT10",
        "MT11",
        "MT13",
        "MT14",
        "MT17",
        "MT19",
        "EC5",
        "EC7",
        "EC9",
        "CT1",
        "CT4",
        "CT5",
        "CT6",
        "CT6B",
        "CT8",
        "CT10",
        "CT13",
        "CT15",
        "CT16",
        "CT18",
        "CT22",
        "CT26",
        "CT26B",
        "UG0",
        "UG1",
        "UG2",
        "UG3",
        "UG3B",
        "UG8",
        "UG10",
        "UG13",
        "UG15",
        "UG20",
        "UW1",
        "UW6",
        "UW8",
        "UW9",
        "UW10",
        "UW11",
        "UW14",
        "UW16",
        "UW16B",
        "UW19",
        "UW23",
        "UW24",
        "UW25",
        "UY1",
        "UY3",
        "UY3B",
        "UY4",
        "UY5",
        "UY7",
        "UY8",
        "UY9",
        "UY9B",
        "UY12",
        "UY12B",
        "UY13",
        "UY17",
        "UY18",
        "OT1",
        "OT2",
        "OT3",
        "OT5",
        "OT8",
        "OT9",
        "OT12",
        "OT13",
        "OT16",
        "OT20",
        "CR1",
        "BA24"
    };

    fprintf(spoiler_log, "Pedestal %s: ", pedestal_rooms[choice]);
}

void writePedestalItem(FILE* spoiler_log, int choice)
{
    char pedestal_items[NUMBER_ITEMS][16] =
    {
        "Dash Boots",
        "Double",
        "Tackle",
        "Kick Boots",
        "Heavy Ring",
        "Cleansing",
        "Roc Wing",
        "Last Key",
        "Map",
        "Heart Max",
        "HP Max",
        "MP Max",
        "Shinning Armor"
    };

    fprintf(spoiler_log, "Item %s\n", pedestal_items[choice]);
}

void writeDSSCard(FILE* spoiler_log, int choice)
{
    char dss_cards[NUMBER_DSSCARDS][16] =
    {
        "Salamander",
        "Serpent",
        "Mandragora",
        "Golem",
        "Cockatrice",
        "Manticore",
        "Griffin",
        "Thunderbird",
        "Unicorn",
        "Black Dog",
        "Mercury",
        "Venus",
        "Jupiter",
        "Mars",
        "Diana",
        "Apollo",
        "Neptune",
        "Saturn",
        "Uranus",
        "Pluto"
    };

    fprintf(spoiler_log, "DSS card %s\n", dss_cards[choice]);
}

void writeEnemy(FILE* spoiler_log, int choice)
{
    char enemies[NUMBER_ENEMIES][32] =
    {
        "Medusa Head",
        "Zombie",
        "Ghoul",
        "Wight",
        "Clinking Man",
        "Zombie Thief",
        "Skeleton",
        "Skeleton Bomber",
        "Electric Skeleton",
        "Skeleton Spear",
        "Skeleton Boomerang",
        "Skeleton Soldier",
        "Skeleton Knight",
        "Bone Tower",
        "Fleaman",
        "Poltergeist",
        "Bat",
        "Spirit",
        "Ectoplasm",
        "Specter",
        "Axe Armor",
        "Flame Armor",
        "Flame Demon",
        "Ice Armor",
        "Thunder Armor",
        "Wind Armor",
        "Earth Armor",
        "Poison Armor",
        "Forest Armor",
        "Stone Armor",
        "Ice Demon",
        "Holy Armor",
        "Thunder Demon",
        "Dark Armor",
        "Wind Demon",
        "Bloody Sword",
        "Golem",
        "Earth Demon",
        "Were-wolf",
        "Man Eater",
        "Devil Tower",
        "Skeleton Athlete",
        "Harpy",
        "Siren",
        "Imp",
        "Mudman",
        "Gargoyle",
        "Slime",
        "Frozen Shade",
        "Heat Shade",
        "Poison Worm",
        "Myconid",
        "Will O'Wisp",
        "Spearfish",
        "Merman",
        "Minotaur",
        "Were-Horse",
        "Marionette",
        "Gremlin",
        "Hopper",
        "Evil Pillar",
        "Were-Panther",
        "Were-Jaguar",
        "Bone Head",
        "Fox Archer",
        "Fox Hunter",
        "Were-Bear",
        "Grizzly",
        "Cerberus",
        "Beast Demon",
        "Arch Demon",
        "Demon Lord",
        "Gorgon",
        "Catoblepas",
        "Succubus",
        "Fallen Angel",
        "Necromancer",
        "Hyena",
        "Fish Head",
        "Dryad",
        "Mimic Candle",
        "Brain Float",
        "Evil Hand",
        "Abiondarg",
        "Iron Golem",
        "Devil",
        "Witch",
        "Mummy",
        "Hippogriff",
        "Adramelech",
        "Arachne",
        "Death Mantis",
        "Alraune",
        "King Moth",
        "Killer Bee",
        "Zombie Dragon",
        "Lizard Man",
        "Franken",
        "Legion",
        "Dullahan",
        "Death",
        "Camilla",
        "Hugh",
        "Dracula I",
        "Dracula II",
        "Skeleton Medalist",
        "Battle Arena Were-Jaguar",
        "Battle Arena Were-Wolf",
        "Battle Arena Catoblepas",
        "Battle Arena Hippogriff",
        "Batlte Arena Wind Demon",
        "Battle Arena Witch",
        "Battle Arena Stone Armor",
        "Battle Arena Devil Tower",
        "Battle Arena Skeleton",
        "Battle Arena Skeleton Bomber",
        "Battle Arena Electric Skeleton",
        "Battle Arena Skeleton Spear",
        "Battle Arena Flame Demon",
        "Battle Arena Bone Tower",
        "Battle Arena Fox Hunter",
        "Battle Arena Poison Armor",
        "Battle Arena Bloody Sword",
        "Battle Arena Abiondarg",
        "Battle Arena Legion",
        "Battle Arena Marionette",
        "Battle Arena Minotaur",
        "Battle Arena Arachne",
        "Battle Arena Succubus",
        "Battle Arena Demon Lord",
        "Battle Arena Alraune",
        "Battle Arena Hyena",
        "Battle Arena Devil Armor",
        "Battle Arena Evil Pillar",
        "Battle Arena Holy Armor",
        "Battle Arena Devil",
        "Scary Candle",
        "Trick Candle",
        "Nightmare",
        "Lilim",
        "Lilith",
    };

    fprintf(spoiler_log, "\n\nEnemy %s\n", enemies[choice]);
}

void writeDropItem(FILE* spoiler_log, int choice)
{
    char dropped_items[NUMBER_ITEMS_INCLUDING_DSS][32] =
    {
        "None",
        "Leather Armor",
        "Bronze Armor",
        "Gold Armor",
        "Chain Mail",
        "Steel Armor",
        "Platinum Armor",
        "Diamond Armor",
        "Mirror Armor",
        "Needle Armor",
        "Dark Armor",
        "Shinning Armor",
        "Cotton Robe",
        "Silk Robe",
        "Rainbow Robe",
        "Magic Robe",
        "Sage Robe",
        "Cotton Clothes",
        "Prison Garb",
        "Stylish Suit",
        "Night Suit",
        "Ninja Garb",
        "Soldier Fatigues",
        "Double Grips",
        "Star Bracelet",
        "Strength Ring",
        "Hard Ring",
        "Intelligence Ring",
        "Luck Ring",
        "Cursed Ring",
        "Strength Armband",
        "Defense Armband",
        "Sage Armband",
        "Gambler Armband",
        "Wrist Band",
        "Gauntlet",
        "Arm Guard",
        "Magic Gauntlet",
        "Miracle Armband",
        "Toy Ring",
        "Bear Ring",
        "Potion",
        "Meat",
        "Spiced Meat",
        "Potion High",
        "Potion Ex",
        "Antidote",
        "Cure Curse",
        "Mind Restore",
        "Mind High",
        "Mind Ex",
        "Heart",
        "Heart High",
        "Heart Ex",
        "Heart Mega",
        "Salamander",
        "Serpent",
        "Mandragora",
        "Golem",
        "Cockatrice",
        "Manticore",
        "Griffin",
        "Thunderbird",
        "Unicorn",
        "Black Dog",
        "Mercury",
        "Venus",
        "Jupiter",
        "Mars",
        "Diana",
        "Apollo",
        "Neptune",
        "Saturn",
        "Uranus",
        "Pluto",
    };

    fprintf(spoiler_log, "%s\n", dropped_items[choice]);
}
